export const columnUserBettedStatistic = {
    team: {
        xxl: 3,
        xl: 4,
        lg: 4,
        md: 5,
        sm: 5,
        xs: 5,
    },
    score: {
        xxl: 3,
        xl: 4,
        lg: 4,
        md: 5,
        sm: 5,
        xs: 6,
    },
    league: {
        xxl: 4,
        xl: 0,
        lg: 0,
        md: 0,
        sm: 0,
        xs: 0,
    },
    matchTime: {
        xxl: 4,
        xl: 4,
        lg: 4,
        md: 0,
        sm: 0,
        xs: 0,
    },
    betChose: {
        xxl: 4,
        xl: 4,
        lg: 4,
        md: 5,
        sm: 5,
        xs: 4,
    },
    betAmount: {
        xxl: 3,
        xl: 4,
        lg: 4,
        md: 4,
        sm: 4,
        xs: 4,
    },
};
