export const routes = {
    homePath: '/',
    loginPath: '/login',
    registerPath: '/register',
    matchPath: '/match',
    matchDetailPath: '/match-detail/:matchId',
    userPath: '/user',
    adminPath: '/admin',
    adminMatchPath: '/admin/match',
    adminUserPath: '/admin/user',
    adminTeamPath: '/admin/team',
    adminLeaguePath: '/admin/league',
    userUpdateInformationPath: '/user/update-information',
    userUpdateAvatarPath: '/user/avatar',
    userUpdatePasswordPath: '/user/password',
    userBettedStatisticPath: '/user/betted-statistic',
    rulesPath: '/bet-rules',
    termsPath: '/terms',
    policyPath: '/privacy-policy',
};
